name:                day6
version:             0.1.0.0
github:              "Kasama/day6"
license:             BSD3
author:              "Roberto Alegro"
maintainer:          "robertoaall@gmail.com"
copyright:           "2020 Roberto Alegro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Kasama/day6#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers
- sort

library:
  source-dirs: src

executables:
  day6-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day6

tests:
  day6-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day6
